# 网站配置

# 引入主题
theme: jekyll-theme-chirpy

# 网页语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果它的值和 `_data/locales` 文件夹中的文件名相同，则布局语言也会被切换，
# 否则默认使用 'en'。
lang: en

# 修改时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone:

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Chirpy # 网站主标题

tagline: A text-focused Jekyll theme # 副标题

description: >- # 用于 SEO meta 和 Atom feed
  一个简约、响应式且功能丰富的 Jekyll 技术写作主题。

# 填写你网站的协议和主机名。
# 例如 'https://username.github.io'，注意不要以 '/' 结尾。
url: ""

github:
  username: github_username # 改为你的 GitHub 用户名

twitter:
  username: twitter_username # 改为你的 Twitter 用户名

social:
  # 修改为你的全名。
  # 它将作为文章默认作者和页脚的版权拥有者显示
  name: your_full_name
  email: example@domain.com # 改为你的邮箱
  links:
    # 第一个链接会作为版权拥有者的主页链接
    - https://twitter.com/username # 改为你的 Twitter 主页
    - https://github.com/username # 改为你的 GitHub 主页
    # 取消注释下面的内容可以添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 网站验证设置
webmaster_verifications:
  google: # 填写 Google 验证码
  bing: # 填写 Bing 验证码
  alexa: # 填写 Alexa 验证码
  yandex: # 填写 Yandex 验证码
  baidu: # 填写百度验证码
  facebook: # 填写 Facebook 验证码

# ↑ --------------------------
# `jekyll-seo-tag` 设置结束

# 网站统计设置
analytics:
  google:
    id: # 填写 Google Analytics ID
  goatcounter:
    id: # 填写 GoatCounter ID
  umami:
    id: # 填写 Umami ID
    domain: # 填写 Umami 域名
  matomo:
    id: # 填写 Matomo ID
    domain: # 填写 Matomo 域名
  cloudflare:
    id: # 填写 Cloudflare Web Analytics token
  fathom:
    id: # 填写 Fathom Site ID

# 页面浏览量统计设置
pageviews:
  provider: # 目前只支持 'goatcounter'

# 配色方案设置
#
# 注意：留空则默认跟随系统设置，
# 并且侧边栏左下角会显示一个切换按钮，可以在亮/暗模式之间切换。
#
# 可选值：
#
#     light — 使用亮色模式
#     dark — 使用暗色模式
#
theme_mode: # [light | dark]

# 媒体资源的 CDN 端点。
# 注意：一旦设置了 CDN url，
# 所有以 '/' 开头的媒体资源路径（头像、文章图片、音频和视频文件）
# 都会被加上 CDN 地址前缀。
#
# 示例: 'https://cdn.com'
cdn:

# 侧边栏的头像，支持本地或跨域（CORS）资源
avatar:

# 网站级社交分享预览图的 URL，用于 SEO 的 `og:image` 标签。
# 可以在文章 Front Matter 中通过 `page.image` 覆盖。
social_preview_image: # 字符串，本地或 CORS 资源

# 全局 TOC（目录）开关，布尔类型
toc: true

comments:
  # 全局评论系统开关。留空表示禁用。
  provider: # [disqus | utterances | giscus]
  # 各评论系统配置如下：
  disqus:
    shortname: # 填写 Disqus shortname › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances 设置 › https://utteranc.es/
  utterances:
    repo: # <gh-用户名>/<仓库>
    issue_term: # < url | pathname | title | ...>
  # Giscus 设置 › https://giscus.app
  giscus:
    repo: # <gh-用户名>/<仓库>
    repo_id:
    category:
    category_id:
    mapping: # 可选，默认 'pathname'
    strict: # 可选，默认 '0'
    input_position: # 可选，默认 'bottom'
    lang: # 可选，默认使用 `site.lang`
    reactions_enabled: # 可选，默认 '1'

# 自托管静态资源（可选）› https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # 布尔值，留空为 false
    # 指定 Jekyll 环境，留空表示开发和生产环境都启用
    # 仅当 `assets.self_host.enabled` 为 'true' 时生效
    env: # [development | production]

pwa:
  enabled: true # PWA 功能开关（允许安装）
  cache:
    enabled: true # PWA 离线缓存开关
    # 定义在这里的路径会被排除在 PWA 缓存之外。
    # 通常它的值是另一个网站的 `baseurl`，
    # 并且与当前网站共享相同域名。
    deny_paths:
      # - "/example"  # 匹配 `<SITE_URL>/example/*` 的 URL 将不会被缓存

# 每页显示文章数
paginate: 10

# 网站的 baseurl
baseurl: ""

# ------------ 以下选项不推荐修改 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge 选项 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # 空字符串表示项目中的所有文件
      type: posts
    values:
      layout: post
      comments: true # 在文章中启用评论
      toc: true # 在文章中显示目录
      # 不要修改以下参数，除非你确定能更新项目中所有其他文章链接
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # 见 `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/